INSERT INTO PUBLIC.TB_CATEGORY (ID, CREATE_DATE, DESCRIPTION, IS_DELETED, NAME)
VALUES (1, null, null, false, 'furniture');
INSERT INTO PUBLIC.TB_CATEGORY (ID, CREATE_DATE, DESCRIPTION, IS_DELETED, NAME)
VALUES (2, null, null, false, 'furniture2');

INSERT INTO PUBLIC.TB_ASSET (ID, CONDITION_NOTE, IS_DELETED, NAME, PURCHASE_DATE, STATUS, CATEGORY_ID, EMPLOYEE_ID)
VALUES (5, null, false, 'desk001', null, 'A', 1, null);